# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name    = "amqp_logging"
  s.version = "0.5.5"

  s.required_rubygems_version = ">= 1.3.1"
  s.authors                   = ["Pascal Friederich"]
  s.date                      = "2010-08-11"
  s.email                     = ["pascal.friederich@xing.com"]
  s.extra_rdoc_files          = ["Readme.rdoc"]
  s.files                     = Dir['lib/**/*.rb']
  s.homepage                  = "http://github.com/paukul/amqp_logging"
  s.rdoc_options              = ["--charset=UTF-8"]
  s.require_paths             = ["lib"]
  s.rubygems_version          = "1.3.5"
  s.summary                   = "A ruby logger class that logs to an AMQP exchange in addition to your default log device."
  s.test_files                = Dir['test/**/*.rb']

  s.post_install_message = <<-INFO
  *********************************************************************************************

    If you're running a ruby version < 1.9 please install the system_timer gem because rubys 
    default timeout.rb isn't reliable.

    "In particular, it is guaranteed to not work in Ruby M.R.I 1.8 when you are issuing 
     system calls that can cause your Ruby process to sleep for a period of time that is 
     longer than your timeout."

    See: http://ph7spot.com/musings/system-timer

  *********************************************************************************************
  INFO

  s.specification_version     = 3
  s.add_runtime_dependency("bunny",                 ["= 0.6.0"])
  s.add_runtime_dependency("bunny-ext",             ["> 0.6.0"])
  s.add_runtime_dependency("activesupport",         [">= 2.3.0"])
  s.add_runtime_dependency("json",                  [">= 1.4.0"])
  s.add_development_dependency("mocha",             [">= 0"])
  s.add_development_dependency("redgreen",          [">= 0"])
end
